apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: instacapture
  name: instacapture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instacapture
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: instacapture
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/rishhabhhanday-dev/instacapture:latest
          name: instacapture
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: insta-capture
                  key: aws.access.key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: insta-capture
                  key: aws.secret.key
            - name: AWS_REGION
              value: ap-south-1
          resources: { }
status: { }
