apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: instacapture
  name: instacapture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instacapture
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: instacapture
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/rishhabhhanday-dev/instacapture:latest
        name: instacapture
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: insta-capture
                key: access_key
          - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: insta-capture
                  key: access_key
          - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: insta-capture
                  key: region
        resources: {}
status: {}
